module.exports = {
  address: '0xe0db3f5bda17d224cb153a80e21559c29c4ff2ac',
  abi: [
    {
      constant: false,
      inputs: [{ name: '_brandOwnerAddress', type: 'address' }],
      name: 'addBrandOwner',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        { name: '_Name', type: 'string' },
        { name: '_Symbol', type: 'string' },
        { name: '_Decimal', type: 'uint8' },
      ],
      name: 'createLoyaltyToken',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: 'contractAddress', type: 'address' }],
      name: 'ContractCreated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: 'brandOwnerAddress', type: 'address' }],
      name: 'BrandOwnerAdded',
      type: 'event',
    },
    {
      constant: true,
      inputs: [],
      name: 'getRegisteredLoyaltyTokens',
      outputs: [{ name: '', type: 'address[]' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: true,
      inputs: [{ name: '', type: 'address' }],
      name: 'isBrandOwner',
      outputs: [{ name: '', type: 'bool' }],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
  ],
}
